name: UCPA WhatsApp Scanner

on:
  schedule:
    - cron: '*/35 6-22 * * *' # Toutes les 20 min de 6h à 22h (Paris)
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    environment: GEMINI_API_KEY # Lien avec tes secrets
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests selenium webdriver-manager

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GREEN_API_URL: ${{ secrets.GREEN_API_URL }}
          WHATSAPP_ID: ${{ secrets.WHATSAPP_ID }}
          COURS_CIBLES: ${{ vars.COURS_CIBLES }}
        run: python ucpa-python.py

      - name: Save memory
        run: |
          git config --global user.name 'Bot UCPA'
          git config --global user.email 'bot@ucpa.com'
          if [ -f memoire_ucpa.json ]; then
            git add memoire_ucpa.json
            git commit -m "Update memory [skip ci]" || echo "No changes"
            git push
          fi
      # 6. Sauvegarde les logs et le HTML pour debug (visible dans l'onglet Actions)
      - name: Upload Logs & Debug Info
        if: always() # S'exécute même si le script a planté
        uses: actions/upload-artifact@v4
        with:
          name: logs-audit-ucpa
          path: |
            execution.log
            debug_page.html
            memoire_ucpa.json
          retention-days: 5

          
