name: UCPA WhatsApp Scanner

on:
  schedule:
    - cron: '*/35 5-22 * * *' # Toutes les 20 min de 6h Ã  22h (Paris)
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    environment: GEMINI_API_KEY # Lien avec tes secrets
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests selenium webdriver-manager

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GREEN_API_URL: ${{ secrets.GREEN_API_URL }}
          WHATSAPP_ID: ${{ secrets.WHATSAPP_ID }}
          COURS_SURVEILLES: ${{ vars.COURS_SURVEILLES }} # <-- Utilise 'vars' si c'est une variable, 'secrets' si c'est un secret          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          FREE_SMS_USER: ${{ secrets.FREE_SMS_USER }} # <--- ICI
          FREE_SMS_PASS: ${{ secrets.FREE_SMS_PASS }} # <--- ICI
                  
        run: python ucpa-python.py

      - name: Save memory
        run: |
          git config --global user.name 'Bot UCPA'
          git config --global user.email 'bot@ucpa.com'
          if [ -f memoire_ucpa.json ]; then
            git add memoire_ucpa.json
            git commit -m "Update memory [skip ci]" || echo "No changes"
            git push
          fi
      # 6. Sauvegarde les logs et le HTML pour debug (visible dans l'onglet Actions)
      
      - name: Upload Debug Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ucpa-debug-log
          path: |
            debug_raw_content.txt
            execution.log
            memoire_ucpa.json
            debug_page.html
            memoire_ucpa.json
          retention-days: 5

          
